### ISSUE TITLE
RxSample doesn't work.

### ISSUE THREAD

**Issue by probepark** [jenzz/RxAppState#12]
```java
RxAppStateMonitor.monitor(this).subscribe(new Action1<AppState>() {
    @Override
    public void call(AppState appState) {
        switch (appState) {
            case FOREGROUND:
                // Hocus Pocus...
                break;
            case BACKGROUND:
                // Abracadabra!
                break;
        }
    }
});
```

RxSample doesn't work.
I think it is not invoked start method, right?

**Comment by jenzz** [comment]
Oops, well spotted.

I didn't notice that as I'm using the traditional callback version using `AppStateListener` -- I will push a fix soon.

**Comment by probepark** [comment]
@jenzz 
Thank you!

**Comment by probepark** [comment]
any update?

**Comment by jenzz** [comment]
Yep. Check out the latest version **[v2.0.1](https://github.com/jenzz/RxAppState/releases/tag/2.0.1)**.

If you still have any issues, feel free to re-open this issue.

**Comment by probepark** [comment]
@jenzz 
Thank you so much your help!
I will check this out soon
