### ISSUE TITLE
Missing artifacts on JCenter

### ISSUE THREAD

**Issue by kenyee** [jenzz/RxAppState#14]
compile "com.jenzz.appstate:appstate:$rxappstate_version"

gives:

Error:Failed to resolve: com.jenzz.appstate:appstate:3.0.0

**Comment by jenzz** [comment]
Hmm it looks like only the [RxJava 2 adapter](https://github.com/jenzz/RxAppState/tree/master/appstate-adapters/rxjava2) artifacts got synced with JCenter...

I will have a look asap.

**Comment by waclock** [comment]
I'm having the same issue trying to install the library from scratch in a new project. Versions 2.0.1 and 2.0.0 don't work, a message appears saying `Failed to resolve: annotationProcessor`. Any help is appreciated

**Comment by y2kshane** [comment]
same issue

**Comment by aviadmini** [comment]
@jenzz I also tried getting it using JitPack but it errors with:
`Error:Module 'com.jenzz:rxappstate:3.0.0' depends on one or more Android Libraries but is a jar`

**Comment by jenzz** [comment]
There seems to be a syncing problem with **JCenter**.

In the meantime you can use **JitPack** to grab the artifacts:

```
allprojects {
  repositories {
    jcenter()
    maven { url 'https://jitpack.io' }
  }
}

compile 'com.jenzz.RxAppState:appstate:3.0.0'
compile 'com.jenzz.RxAppState:adapter-rxjava:3.0.0'
compile 'com.jenzz.RxAppState:adapter-rxjava2:3.0.0'
```

**Comment by jenzz** [comment]
The artifacts are now available on **JCenter** via the original namespace.
No more **JitPack** required.

```
compile 'com.jenzz.appstate:appstate:3.0.0'
compile 'com.jenzz.appstate:adapter-rxjava:3.0.0'
compile 'com.jenzz.appstate:adapter-rxjava2:3.0.0'
```
https://oss.sonatype.org/content/repositories/releases/com/jenzz/appstate/
