### ISSUE TITLE
It doesn't work on RedMi Note 4

### ISSUE THREAD

**Issue by chihung93** [jenzz/RxAppState#16]
Phone: RedMi Note 4
Android: 6.0.1 MMB29M

It just works with this steps:
Step 1: Open App
Step 2: Press Home on device
Step 3: Open app again from the main screen of device ( List all app in device )

It doesn't work with this steps:
Step 1: Open App
Step 2: Press Home on device
Step 3: Press Overview button
Step 4: click App
=> RxAppState can't detect this case.

**Comment by jenzz** [comment]
I cannot reproduce this issue on a device running Marshmallow. It works fine via the overview / recent apps button.

This might be a bug only occurring on Xiaomi OS...?

**Comment by chihung93** [comment]
@jenzz yes, Just on Xiaomi OS

**Comment by jenzz** [comment]
I'm closing this issue as it seems to be happening only on Xiaomi OS and I do not have such a device or emulator to reproduce it.

Please re-open if you have more information.
