### ISSUE TITLE
when i start other app the front app is also in Foreground

### ISSUE THREAD

**Issue by wangchengyan** [jenzz/RxAppState#17]
when i start other app the front app is also in Foreground Unless the other app goto next Activity  why ?  please help me !!

**Comment by jenzz** [comment]
I don't understand the problem. What do you mean by "the front app is also in foreground"?

**Comment by wangchengyan** [comment]
sorry my english is very bad ! 
A  app  launch B app  
if  B  in MainActivity  A  is also in the  foreground 
unless B  go to another activity ,when B back to MainActivity A in the  foreground again

**Comment by jenzz** [comment]
@wangchengyan, can you provide a sample app that reproduces this issue?

**Comment by jenzz** [comment]
Closing this issue. Please re-open if you can provide steps to reproduce.
