### ISSUE TITLE
Remove hard dependency on RxJava

### ISSUE THREAD

**Issue by jenzz** [jenzz/RxAppState#4]
Even though it is pretty much standard (?) in Android world nowadays and the name of the library implies it,
this library should probably not depend on RxJava.

Instead an additional, reactive adapter could be provided, e.g. **com.jenzz:appstate-rx:2.0.0**

**Comment by andrewlord1990** [comment]
Another possibility could be a provided dependency. That way if you call .subscribe() without having the RxJava dependency it will crash. 
This is similar to how Retrofit 1 worked, where it could return Observables without having a dependency on RxJava.

**Comment by jenzz** [comment]
\- Done via https://github.com/jenzz/RxAppState/commit/3ea68fedc7449078851aedae5911a8d11079e38d -
