### ISSUE TITLE
Can't get dependency

### ISSUE THREAD

**Issue by andrewlord1990** [jenzz/RxAppState#6]
When I try to include RxAppState into the project I had JitPack added and add the library dependency. I just get:

'Could not find com.jenzz:RxAppState:1.1.0'

**Comment by jenzz** [comment]
Hmm I just tried it myself with a brand-new project and it works just fine.
**v1.1.0** is definitely available online: https://jitpack.io/com/jenzz/RxAppState/1.1.0/build.log

If you show me your full Gradle file, I might be able to help you out.
Or have you enabled **offline mode** in Android Studio?

**Comment by andrewlord1990** [comment]
Oh okay thanks. I will evaluate my project and try and work it out. I have offline disabled, I have problems with JitPack every time I use a new library that uses JitPack, I would always advise Bintray and JCenter instead. Thanks for checking for me, I am sure there is just something wrong in my environment.
