### ISSUE TITLE
BACKGROUND event sent when turning screen off even when the app was already on background

### ISSUE THREAD

**Issue by mbarrben** [jenzz/RxAppState#8]
Turning the screen off issues a BACKGROUND event every time, no matter whether the app was previously on FOREGROUND or BACKGROUND.

This can be easily workarounded using Rx `distinctUntilChanged()` method though.

**Comment by jenzz** [comment]
Ugh. Thanks for reporting.

I will fix it with the next update.

**Comment by jenzz** [comment]
\- Fixed via #10 -
